[package]
name = "data_access"
version = "0.1.0"
authors = ["Web3 CRM Team"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]
ink-as-dependency = []

[profile.release]
overflow-checks = false

[[test]]
name = "integration"
path = "integration_tests.rs"
