-- Ensure RLS is DISABLED on all ownbase tables for demo

ALTER TABLE IF EXISTS ownbase_data_vault DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_earnings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_deals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_data_access_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ownbase_users DISABLE ROW LEVEL SECURITY;
